# Build pipeline for Develop Branch

variables:
  solutionName: SmartDi.sln
  projectName: SmartDi.csproj

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Load Nuget Tool'
  inputs:
    versionSpec: '4.5.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/$(solutionName)'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/$(projectName)'
    configuration: 'Release'
    msbuildArguments: '-t:restore;build;pack -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/beta'
#/p:PackageVersion=$(Build.BuildNumber)-beta
#/p:AssemblyFileVersion=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
