# Build pipeline for Develop Branch

variables:
  solutionName: SmartDi.sln

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/$(solutionName)'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/$(solutionName)'
    configuration: 'Release'
    msbuildArguments: '/t:restore; build; pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/beta /p:AssemblyFileVersion=$(Build.BuildNumber)'

