# Build pipeline for Develop Branch

# This sets $(Build.BuildNumber)
name: $(Date:yyyyMMdd).$(Rev:r)

# Set project names here
variables:
  projectName: SmartDi.csproj

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

# Implicit Restore run before build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/$(projectName)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/$(projectName)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/alpha'
    nobuild: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'

# Note, we're outputing to */alpha to differentiate pre-release
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/$(projectName)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/alpha'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
