# Build pipeline for Master Branch

# This sets $(Build.BuildNumber)
name: 1.3.$(Rev:r)

# Set project names here
variables:
  projectName: SmartDi.csproj
  testProjectName: SmartDiTests.csproj

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
## - Build Project -
# Implicit Restore is run before build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/$(projectName)'
    arguments: '--configuration Release'

## - Run Unit Tests -
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/$(testProjectName)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration Release --collect:"XPlat Code Coverage"'
    publishTestResults: true
    projects: '**/$(testProjectName)'


## - Pack -
# Package with -pre version for /beta
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/$(projectName)'
    configuration: 'Release'
    packDirectory: '$(Build.ArtifactStagingDirectory)/beta'
    nobuild: true
    versioningScheme: 'off'
    buildProperties: 'PackageVersion=$(Build.BuildNumber)-pre'

# Package public version off same build
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/$(projectName)'
    configuration: 'Release'
    packDirectory: '$(Build.ArtifactStagingDirectory)/public'
    nobuild: true
    versioningScheme: 'off'
    buildProperties: 'PackageVersion=$(Build.BuildNumber)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
