# Build pipeline for Develop Branch

variables:
  solutionName: SmartDi.sln

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/$(solutionName)'
    feedsToUse: 'select'

