# Build pipeline for Develop Branch

# Set buildnumber here
#$(Date:yyyyMMdd).$(Rev:r)-alpha
name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  solutionName: SmartDi.sln
  projectName: SmartDi.csproj

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/$(solutionName)'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/$(projectName)'
    configuration: 'Release'
    msbuildArguments: '-t:restore;build;pack -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/alpha -p:PackageVersion=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
