# Build pipeline for Develop Branch

# This sets $(Build.BuildNumber)
name: $(Date:yyyyMMdd).$(Rev:r)

# Set project names here
variables:
  solutionName: SmartDi.sln
  projectName: SmartDi.csproj

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/$(solutionName)'
    feedsToUse: 'select'

# Note, we're outputing to */alpha to differentiate pre-release
- task: MSBuild@1
  inputs:
    solution: '**/$(projectName)'
    configuration: 'Release'
    msbuildArguments: '-t:restore;build;pack -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/alpha -p:PackageVersion=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
